### ISSUE TITLE
Original node software support

### ISSUE THREAD

**Issue by lifengmds** [libsv/go-bt#105]
As this lib is based on full node running on bsvd, I wonder if it can support RPC connection on official bitcoind node?
It seems bsvd couldn't keep up with official upgrades, so it will also raise issues on go-bt I guess...

**Comment by Tigh-Gherr** [comment]
Hey @lifengmds thanks for reaching out.

I think the functionality you're requesting can be found in our go-bn lib, https://github.com/libsv/go-bn

It's currently in pre-release so feel free to use it and report any issues you come across.
